# Generated by Django 2.1.2 on 2018-12-11 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0003_dataprocess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetails',
            name='mimic_data',
            field=models.TextField(null=True),
        ),
    ]
