# Generated by Django 2.1.2 on 2018-12-27 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0005_auto_20181213_1305'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dataprocess',
            table='dataprocess',
        ),
        migrations.AlterModelTable(
            name='projectdetails',
            table='project',
        ),
    ]
