# Generated by Django 2.1.2 on 2018-12-27 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_management', '0006_table_rename'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectComponents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_name', models.CharField(max_length=120)),
                ('reference_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'project_component',
            },
        ),
        migrations.RenameField(
            model_name='projectdetails',
            old_name='mimic_data',
            new_name='project_design_json',
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='Description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectcomponents',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='project_management.ProjectDetails'),
        ),
        migrations.AddField(
            model_name='projectcomponents',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
