# Generated by Django 2.1.2 on 2018-12-28 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tag_management', '0006_auto_20181228_1902'),
        ('project_management', '0007_project_component'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectComponentsTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components_tags_compt', to='project_management.ProjectComponents')),
            ],
            options={
                'db_table': 'project_components_tags',
            },
        ),
        migrations.RemoveField(
            model_name='projectdetails',
            name='Description',
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='projectcomponentstags',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components_tags_proj', to='project_management.ProjectDetails'),
        ),
        migrations.AddField(
            model_name='projectcomponentstags',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components_tags_tg', to='tag_management.TagDetails'),
        ),
    ]
