# Generated by Django 2.1.2 on 2019-01-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0008_auto_20181228_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcomponentstags',
            name='is_active',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
