# Generated by Django 2.1.2 on 2019-01-04 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tag_management', '0006_auto_20181228_1902'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_management', '0009_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentsLibrary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('default_image', models.CharField(max_length=120)),
                ('status_on', models.CharField(max_length=120)),
                ('status_off', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('component_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libraries', to='tag_management.TagType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lib_creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project_component_libraries',
            },
        ),
    ]
