# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-01-09 06:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0010_componentslibrary'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcomponents',
            name='component_library',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='library', to='project_management.ComponentsLibrary'),
        ),
    ]
