# Generated by Django 2.1.2 on 2019-01-21 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0012_complibdigitalnotify'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetails',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
