# Generated by Django 2.1.2 on 2018-12-27 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_management','__first__'),
        ('tag_management', '0003_tag_fields_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagdetails',
            name='component_name',
            field=models.CharField(max_length=120),
        ),
        migrations.AddField(
            model_name='tagdetails',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tag_details', to='project_management.ProjectDetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tagdetails',
            name='tag_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tag_type', to='TagType'),
            preserve_default=False,
        ),
    ]
