# Generated by Django 2.1.2 on 2018-12-27 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag_management', '0004_tag_fields_modified'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tagdetails',
            table='tags',
        ),
        migrations.AlterModelTable(
            name='tagtype',
            table='tagtype',
        ),
    ]
