# Generated by Django 2.1.2 on 2018-12-28 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tag_management', '0005_table_rename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagdetails',
            name='component_name',
        ),
        migrations.RemoveField(
            model_name='tagdetails',
            name='project',
        ),
        migrations.RemoveField(
            model_name='tagdetails',
            name='tag_id',
        ),
        migrations.AddField(
            model_name='tagdetails',
            name='description',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tagdetails',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tags_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
