# Generated by Django 2.1.2 on 2019-01-21 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag_management', '0006_auto_20181228_1902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tagdetails',
            old_name='name',
            new_name='tag_name',
        ),
        migrations.AddField(
            model_name='tagdetails',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
