# Generated by Django 2.1.2 on 2019-02-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag_management', '0007_auto_20190121_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagtype',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
