# Generated by Django 2.1.2 on 2019-03-01 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tag_management', '0008_tagalarm_tagconversioncode_tagparameter_tagscantype'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagdetails',
            name='address',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='tagdetails',
            name='alarm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag_alarm', to='tag_management.TagAlarm'),
        ),
        migrations.AddField(
            model_name='tagdetails',
            name='conversion_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag_conversion_code', to='tag_management.TagConversionCode'),
        ),
        migrations.AddField(
            model_name='tagdetails',
            name='data_log_dead_band',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tagdetails',
            name='initial_value',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tagdetails',
            name='keep_previous_value',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='tagdetails',
            name='length',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tagdetails',
            name='log_data',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='tagdetails',
            name='parameter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag_parameter', to='tag_management.TagParameter'),
        ),
        migrations.AddField(
            model_name='tagdetails',
            name='read_only',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='tagdetails',
            name='scan_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag_scan_type', to='tag_management.TagScanType'),
        ),
        migrations.AddField(
            model_name='tagdetails',
            name='security_area',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tagdetails',
            name='security_level',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tagdetails',
            name='signal_reverse',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='tagdetails',
            name='start_bit',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tagdetails',
            name='status_one',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='tagdetails',
            name='status_zero',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='tagdetails',
            name='write_action_log',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='tagdetails',
            name='tag_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag_type', to='tag_management.TagType'),
        ),
    ]
