# Generated by Django 2.1.2 on 2019-03-12 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag_management', '0009_auto_20190301_1637'),
        ('tag_management', '0008_tagtype_deleted'),
    ]

    operations = [
    ]
