# Generated by Django 2.1.2 on 2018-10-11 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djmongo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile_no',
            field=models.BigIntegerField(unique=True),
        ),
    ]
