# Generated by Django 2.1.2 on 2019-03-13 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0014_auto_20190207_1910'),
        ('djmongo', '0006_passwordreset'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_projects', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_project_id', to='project_management.ProjectDetails')),
                ('analog_tag', models.BigIntegerField(null=True)),
                ('digital_tag', models.BigIntegerField(null=True)),
                ('video_tag', models.BigIntegerField(null=True)),
                ('audio_tag', models.BigIntegerField(null=True)),
                ('is_active', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(editable=False, null=True)),
            ],
            options={
                'db_table': 'iot_user_project',
            },
        ),
    ]
