# Generated by Django 2.1.2 on 2019-03-13 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djmongo', '0007_userproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
